# Generated by Django 3.2.8 on 2022-05-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFeeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('felling', models.CharField(max_length=50)),
                ('datetimes', models.CharField(max_length=50)),
            ],
        ),
    ]
