# Generated by Django 3.2.8 on 2022-05-05 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dailyfeeling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyfeeling',
            old_name='felling',
            new_name='feeling',
        ),
    ]
